### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by drothmaler** [ryangray/buttondown#2]
Please add a license to the repo/files.

**Comment by nyh** [comment]
I also have this problem - I want to use your very nice buttondown.css to produce the documentation in the documentation of an open-source project (http://www.seastar-project.org/) but I can't do that if I don't know that I can redistribute the buttondown.css file... Can you please clarify if this file is public domain, or has some specific license, or what? Thanks!

**Comment by ryangray** [comment]
Sorry, I kept forgetting to do this. I've included a public domain license. 

I also really need to check more recent Pandoc and MultiMarkdown output to see if changes require me to revise the CSS rules.
